site_name: Laravel Azampay
site_description: 'Laravel integration for Azampay payment gateway'
site_author: 'Intelfric technologies company limited'
docs_dir: docs/
repo_name: 'intelfric/laravel-azampay'
repo_url: 'https://github.com/intelfric/laravel-azampay'
nav:
    - Home: index.md
theme:
  name: 'material'
